package main

import (
	"fmt"
	mapreduce "laboratorio-4/pkg"
	"os"
	"sort"
	"strconv"
	"strings"
	"unicode"
)

// The mapping function is called once for each piece of the input.
// In this framework, the key is the name of the file that is being processed,
// and the value is the file's contents. The return value should be a slice of
// key/value pairs, each represented by a mapreduce.KeyValue.
func mapF(document string, value string) (res []mapreduce.KeyValue) {
	// Parte 5
	var word_doc []mapreduce.KeyValue
	IsLetter := func(y rune) bool { // divide el string en algo que no sea letras
		return !unicode.IsLetter(y)
	}
	for _, word := range strings.FieldsFunc(value, IsLetter) {
		word_doc = append(word_doc, mapreduce.KeyValue{word, document})
	}
	return word_doc
}

// The reduce function is called once for each key generated by Map, with a
// list of that key's string value (merged across all inputs). The return value
// should be a single output value for that key.
func reduceF(key string, values []string) string {
	// Codigo modificado para parte 5
	set := make(map[string]float64)
	for _, val := range values {
		set[val] = 1
	}
	var docs []string
	for key, _ := range set {
		docs = append(docs, key)
	}
	sort.Strings(docs)
	return strconv.Itoa(len(docs)) + " " + strings.Join(docs, ",")
}

// Can be run in 3 ways:
// 1) Sequential (e.g., go run wc.go master sequential x1.txt .. xN.txt)
// 2) Master (e.g., go run wc.go master localhost:7777 x1.txt .. xN.txt)
// 3) Worker (e.g., go run wc.go worker localhost:7777 localhost:7778 &)
func main() {
	if len(os.Args) < 4 {
		fmt.Printf("%s: see usage comments in file\n", os.Args[0])
	} else if os.Args[1] == "master" {
		var mr *mapreduce.Master
		if os.Args[2] == "sequential" {
			mr = mapreduce.Sequential("iiseq", os.Args[3:], 3, mapF, reduceF)
		} else {
			mr = mapreduce.Distributed("iiseq", os.Args[3:], 3, os.Args[2])
		}
		mr.Wait()
	} else {
		mapreduce.RunWorker(os.Args[2], os.Args[3], mapF, reduceF, 100)
	}
}
